[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-doc-qa"
version = "1.0.0"
description = "Production-ready Retrieval-Augmented Generation system for document QA"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
maintainers = [
    {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic"
]
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",  # For CUDA version: install with pip install torch --index-url https://download.pytorch.org/whl/cu118
    "transformers>=4.30.0",
    "sentence-transformers>=2.2.0",
    "faiss-gpu>=1.7.0",  # Use faiss-cpu for CPU support
    "PyPDF2>=3.0.0",
    "beautifulsoup4>=4.12.0",
    "chardet>=5.0.0",
    "requests>=2.31.0",
    "rank-bm25>=0.2.2",
    "numpy>=1.24.0",
    "gradio>=4.0.0",
    "python-dotenv>=1.0.0",
    "scikit-learn>=1.3.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "mypy>=1.5.0"
]
openai = [
    "openai>=1.0.0"
]
gpu = [
    "faiss-gpu>=1.7.0"
]

[project.urls]
Homepage = "https://github.com/yourusername/rag-doc-qa"
Documentation = "https://github.com/yourusername/rag-doc-qa#readme"
Repository = "https://github.com/yourusername/rag-doc-qa"
Issues = "https://github.com/yourusername/rag-doc-qa/issues"

[project.scripts]
rag-qa = "rag_doc_qa.web_app:main"
rag-eval = "rag_doc_qa.evaluate:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["rag_doc_qa"]

[tool.setuptools.package-data]
rag_doc_qa = ["*.json", "*.yaml", "*.yml"]

[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-ra -v --cov=src/rag_doc_qa --cov-report=term-missing"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = true
